branches:
  only:
  - tatyano
sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install:
- eval "$(gimme 1.7.3)"
- nvm install 6
- npm install -g npm@latest
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update
- sudo apt-get install gcc-4.8
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
- sudo apt-get install g++-4.8
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
script: mvn install -DargLine="-Dlogback.configurationFile=src/test/resources/travis_logback.xml"
after_success:
- test "${TRAVIS_PULL_REQUEST}" == "false" && ./docker/publish_docker.sh
env:
  global:
